name: Gradle build

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]
jobs:
  build_and_test:
    if: github.repository_owner == 'Muspah'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          architecture: x64
          distribution: 'temurin'
      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with gradle
        run: ./gradlew build
      # Install our SSH key:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        if: ${{ github.event_name == 'push' }}
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
      # Mark our scripts runnable:
      - name: Mark deploy script runnable
        if: ${{ github.event_name == 'push' }}
        run: chmod +x "${GITHUB_WORKSPACE}/.github/deploy.sh"
      # Deploy to webserver:
      - name: Run deploy script
        if: ${{ github.event_name == 'push' }}
        run: "${GITHUB_WORKSPACE}/.github/deploy.sh"
